{{- if .Values.appserver.istio.enabled -}}
{{- if not .Values.appserver.istio.gateway.host -}}
{{- fail "appserver: You must set a host if istio(enabled)" -}}
{{- end -}}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ template "chirpstack.appserver.fullname" . }}
  labels:
{{ include "chirpstack.appserver.labels" . | indent 4 }}
spec:
  selector:
    istio: {{default "ingressgateway" .Values.appserver.istio.gateway.selector }}
  servers:
  - hosts:
    - {{ .Values.appserver.istio.gateway.host }}
    port:
      name: http-{{ template "chirpstack.appserver.fullname" . }}
      number: 80
      protocol: HTTP2
{{- if .Values.appserver.istio.gateway.tls.enabled }}
    tls:
      httpsRedirect: true
  - hosts:
    - {{ .Values.appserver.istio.gateway.host }}
    port:
      name: https-{{ template "chirpstack.appserver.fullname" . }}
      number: 443
      protocol: HTTPS
    tls:
{{- if not .Values.appserver.istio.gateway.tls.credentialName -}}
{{- fail "appserver: You must set a credentialName if tls(enabled)" -}}
{{ end }}
      credentialName: {{ .Values.appserver.istio.gateway.tls.credentialName }}
      mode: SIMPLE
      privateKey: sds
      serverCertificate: sds
{{ end }}

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "chirpstack.appserver.fullname" . }}
  labels:
{{ include "chirpstack.appserver.labels" . | indent 4 }}
spec:
  hosts:
  - {{ .Values.appserver.istio.gateway.host }}
  gateways:
  - {{ template "chirpstack.appserver.fullname" . }}
  http:
  - match:
  {{- if .Values.appserver.istio.gateway.tls.enabled }}
    - port: 443
  {{- end }}
    - port: 80 
    route:
    - destination:
        host: {{ template "chirpstack.appserver.fullname" . }}-external
        port:
          number: 8080
{{- end -}}