apiVersion: v1
appVersion: 1.30.3
description: Official Gravitee.io Helm chart for API Management
home: https://gravitee.io
icon: https://avatars2.githubusercontent.com/u/12655666?s=200&v=4
name: apim
sources:
- https://github.com/gravitee-io
version: 1.29.3
