{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "quantumleap.fullname" . }}
  labels:
    app: {{ template "quantumleap.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.yml: |
{{ toYaml .Values.config | trim | indent 4 }}
{{- end }}
